In [2]:
import numpy as np

In [3]:
c=np.array([[1,2],[3,4]])

In [4]:
print(c)

[[1 2]
 [3 4]]


In [5]:
print(c.shape)

(2, 2)


In [8]:
a=np.random.random((4,4))

In [9]:
a=np.random.randint((4,4))

In [10]:
print (a)

[0 3]


In [12]:
b=np.random.randint(0,10,(4,4))

In [13]:
print (b)

[[4 1 5 8]
 [8 6 1 6]
 [9 4 0 0]
 [1 9 2 3]]


In [15]:
print (b.transpose())

[[4 8 9 1]
 [1 6 4 9]
 [5 1 0 2]
 [8 6 0 3]]


In [21]:
d=b.transpose()

In [17]:
result=np.dot(c,d)

In [18]:
print (result)

[[ 5 11]
 [11 25]]


In [24]:
result1=np.dot(b,d)

In [25]:
print(result1)

[[106  91  40  47]
 [ 91 137  96  82]
 [ 40  96  97  45]
 [ 47  82  45  95]]
